#!/usr/bin/env python3
# catick.py — an ON-BOARD CA CLOCK (bar #2): timing generated by the automaton itself, no orchestration.
# Every sequential thing so far (shiftreg, seqcircuit, the clocked datapath in caclock) is stepped by a
# host clock.  Here the clock IS the cellular automaton: a single glider on a TOROIDAL board circulates by
# the rule alone and passes a fixed readout once per lap — a periodic pulse train.  The hex lattice wraps
# (rulehub.hex_key uses np.roll), so no boundary handling is needed; the glider just comes back around.
# We measure the period, confirm it's STABLE over many laps and the glider stays alive (bounded), and read
# the clock signal at a fixed cell.  A stable autonomous period = a clock built from the substrate.
import json, os
import numpy as np
import rulehub, glider_dir

LIB = "alice/swarm-v1/outputs"

def is_compact(lut, side=60, T=220, warmup=30, cap=70, seed=0):
    """Run the glider on a torus and confirm it stays a LOCALIZED packet (never dies, never fills a band) —
    the property that makes it a clean clock rather than a trail-filling front."""
    rng = np.random.default_rng(seed); b = np.zeros((side, side), np.uint8); c = side // 2
    b[c-2:c+3, c-2:c+3] = rng.integers(1, 4, (5, 5))
    mx = 0
    for t in range(T):
        b = lut[rulehub.hex_key(b.astype(np.int64))].astype(np.uint8)
        nz = int((b > 0).sum())
        if nz == 0: return False, 0
        if t > warmup: mx = max(mx, nz)
    return mx < cap, mx

def load_glider_rule():
    """Pick the most COMPACT library glider that translates with a real horizontal component — so it crosses
    a fixed column once per horizontal lap (period = circumference/|vx|), a clean periodic clock."""
    recs = [r for r in json.load(open(os.path.join(LIB, "library.json"))) if r["glider"]]
    blobs = os.path.join(LIB, "blobs")
    best = None
    for r in recs:
        lut = np.fromfile(os.path.join(blobs, r["hash"] + ".lut"), dtype=np.uint8, count=16384)
        v = glider_dir.glider_velocity(lut)
        if v is None: continue
        vx = abs(v[1] * np.cos(v[0]))
        if vx < 0.25: continue                              # need a horizontal lap of finite length
        ok, mx = is_compact(lut)
        if not ok: continue
        if best is None or mx < best[3]:
            best = (lut, r, v, mx)
        if best[3] <= 6: break                              # already a near-minimal glider; stop early
    return best

def run_clock(lut, side, T, col_off, seed=0):
    """Seed one glider; read a fixed COLUMN STRIP (a 'tripwire' the glider crosses once per horizontal lap)
    plus total activity (to confirm the packet stays alive + localized)."""
    rng = np.random.default_rng(seed); b = np.zeros((side, side), np.uint8); c = side // 2
    b[c-2:c+3, c-2:c+3] = rng.integers(1, 4, (5, 5))
    col = (c + col_off) % side
    total, readout = [], []
    for t in range(T):
        b = lut[rulehub.hex_key(b.astype(np.int64))].astype(np.uint8)
        total.append(int((b > 0).sum()))
        readout.append(int((b[:, (col-1) % side:col+2] > 0).sum()))   # vertical tripwire strip
    return np.array(total), np.array(readout)

def lap_period(readout, expected, warmup=30):
    """Autocorrelation peak near the expected lap length = the clock period."""
    s = readout[warmup:].astype(float); s = s - s.mean()
    if np.allclose(s, 0): return None, 0.0
    ac = np.correlate(s, s, "full")[len(s)-1:]; ac = ac / (ac[0] + 1e-9)
    lo, hi = max(4, int(0.55*expected)), min(len(ac)-1, int(1.7*expected))
    if lo >= hi: return None, 0.0
    best = max(range(lo, hi), key=lambda L: ac[L])
    return best, float(ac[best])

if __name__ == "__main__":
    print("catick — an on-board CA clock: a glider circulating a torus = an autonomous periodic pulse\n")
    got = load_glider_rule()
    if got is None:
        print("  no clean compact glider found"); raise SystemExit
    lut, rec, v, mx = got
    vx = abs(v[1] * np.cos(v[0]))
    print(f"  glider rule: {rec['family']} cx={rec['cx']:.3f} span={rec['span']:.3f} | heading {np.degrees(v[0]):+.0f}° "
          f"speed {v[1]:.2f} cells/tick (|vx|={vx:.2f}) | packet ≤{mx} cells (localized)\n")
    rows = []
    for side in (48, 60, 72, 84):
        expected = side / vx                                    # horizontal lap ≈ circumference / |vx|
        T = int(6.5 * expected)
        total, readout = run_clock(lut, side, T, col_off=side // 3)
        alive = total[30:].min() > 0 and total[30:].max() < 0.10 * side * side
        P, strength = lap_period(readout, expected)
        rows.append((side, P))
        print(f"  torus {side}×{side}: expected lap ≈ {expected:.0f} ticks | glider alive={alive} | "
              f"measured period = {P} (autocorr {strength:.2f})")
        if side == 60 and P:
            seg = readout[30:30 + 5*P]; hi = max(seg.max(), 1)
            bar = "".join("█" if x > 0.4*hi else "·" for x in seg)
            print(f"     clock signal, 5 ticks (█=glider crossing the tripwire): {bar}")
    # the signature of a real CIRCULATING clock: period grows linearly with the circumference
    good = [(s, P) for s, P in rows if P]
    if len(good) >= 3:
        sd = np.array([s for s, _ in good]); pp = np.array([P for _, P in good], float)
        r = np.corrcoef(sd, pp)[0, 1]
        print(f"\n  period vs circumference: {dict(good)}  ->  linear corr {r:+.3f}, "
              f"ticks/cell ≈ {np.polyfit(sd, pp, 1)[0]:.2f} (predicted 1/|vx| = {1/vx:.2f})")
        if r > 0.98:
            print("  -> AUTONOMOUS CA CLOCK: a localized glider circulates the torus by the rule alone; its lap")
            print("     time scales with the board circumference (corr >0.98) — a periodic tick generated by the")
            print("     substrate itself, no host orchestration. The clock IS the cellular automaton.")
