# Generated by Django 6.0.3 on 2026-06-13 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_id', models.IntegerField()),
                ('brain_path', models.CharField(help_text='relative to run.run_dir', max_length=300)),
                ('mapbits', models.IntegerField(default=22)),
                ('orders', models.CharField(default='2,4,7', max_length=40)),
                ('marginal', models.FloatField(default=0.0)),
                ('n_owned', models.IntegerField(default=0)),
                ('centroid', models.FloatField(default=0.0)),
                ('pos_lo', models.FloatField(default=0.0)),
                ('pos_hi', models.FloatField(default=0.0)),
                ('label', models.CharField(blank=True, max_length=60)),
                ('terms', models.TextField(blank=True)),
                ('sample', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-n_owned', 'expert_id'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('run_dir', models.CharField(help_text='absolute path to the run output dir', max_length=500)),
                ('atn_path', models.CharField(help_text='absolute path to the atn binary', max_length=500)),
                ('corpus_path', models.CharField(blank=True, max_length=500)),
                ('coverage_bpb', models.FloatField(default=0.0)),
                ('config_json', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='corpus.expert')),
            ],
        ),
        migrations.AddField(
            model_name='expert',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experts', to='corpus.run'),
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1)),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='corpus.expert')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='corpus.expert')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='corpus.run')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='expert',
            unique_together={('run', 'expert_id')},
        ),
    ]
