# Generated by Django 6.0.3 on 2026-06-13 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen', models.IntegerField()),
                ('coverage_bpb', models.FloatField(default=0.0)),
                ('best_marginal', models.FloatField(default=0.0)),
                ('n_owners', models.IntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='corpus.run')),
            ],
            options={
                'ordering': ['gen'],
            },
        ),
    ]
